version: '3.9'

services:

  # keycloak db
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: password
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  server:
    build: 
      context: /server
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REALM: fra-realm
    ports:
      - "5000:5000"
    depends_on:
      - redis
  
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - keycloak
      - server
      - redis
    extra_hosts:
      - "fra.com:192.168.1.207" # change it with "sudo nano /etc/hosts" with your domain name and your ip address


volumes:
  cache:
    driver: local