version: '3.9'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: server_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql

  server:
    build: 
      context: server
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 5000
      JWT_KEY: 123123

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

      USER: admin
      PASSWORD: admin
      HOST: postgres
      DATABASE: server_db
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data


volumes:
  cache:
    driver: local
  postgres:
    driver: local